[versions]
composecompiler = "1.4.6"
coroutines = "1.7.3"
desugar_jdk_libs = "2.0.3"
espresso = "3.5.1"
gradleplugin = "8.0.2"
hilt = "2.47"
kotlin = "1.8.20"
lifecycle = "2.6.2"
room = "2.5.2"
ktor = "2.2.2"
splash = "1.0.1"
firebaseCrashlyticsPlugin = "2.9.9"
firebasePerfPlugin = "1.4.2"
junit4 = "4.13.2"
agp = "7.4.2"
chucker = "4.0.0"
ksp = "1.8.20-1.0.11"
androidxComposeBom = "2023.09.00"
remote_config = "21.4.1"

[libraries]
android-appCompat = "androidx.appcompat:appcompat:1.6.1"
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
android-coreKtx = "androidx.core:core-ktx:1.10.1"
android-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
android-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
android-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.1.0-alpha01"
android-hilt-androidx-compiler = "androidx.hilt:hilt-compiler:1.0.0"
android-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
android-material = "com.google.android.material:material:1.9.0"
android-test-compose = { group = "androidx.compose.ui", name = "ui-test-junit4" }
android-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
android-test-idling = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "espresso" }
android-test-junit4 = "androidx.test.ext:junit:1.1.5"
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splash" }
coil-compose = "io.coil-kt:coil-compose:2.4.0"
compose-activity = "androidx.activity:activity-compose:1.7.2"
compose-compiler = "androidx.compose.compiler:compiler:1.4.6"
compose-material-3 = { group = "androidx.compose.material3", name = "material3" }
compose-materialIcons = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-runtimeLivedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-preview-customview = "androidx.customview:customview:1.2.0-alpha02"
compose-preview-customview-poolingcontainer = "androidx.customview:customview-poolingcontainer:1.0.0"
compose-constraintlayout = "androidx.constraintlayout:constraintlayout-compose:1.1.0-alpha12"
compose-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-compose:2.6.1"
accompanist-swiperefresh = "com.google.accompanist:accompanist-swiperefresh:0.27.0"
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
gson-gson = "com.google.code.gson:gson:2.10.1"
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-coroutines-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"
kotlin-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
gms-play-services-auth = "com.google.android.gms:play-services-auth:20.7.0"
lifecycle-livedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lottie-compose = "com.airbnb.android:lottie-compose:6.0.0"
paging-common = "androidx.paging:paging-common-ktx:3.2.1"
paging-compose = "androidx.paging:paging-compose:3.2.1"
result-jvm = "com.github.kittinunf.result:result-jvm:5.2.1"
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
datastore = "androidx.datastore:datastore-preferences:1.0.0"
timber = "com.jakewharton.timber:timber:5.0.1"
test-androidx-core = "androidx.test:core-ktx:1.5.0"
test-robolectric = "org.robolectric:robolectric:4.10.3"
test-navigation = "androidx.navigation:navigation-testing:2.7.2"
test-mockk = "io.mockk:mockk:1.12.7"
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
firebase-bom = "com.google.firebase:firebase-bom:32.2.3"
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-performance = { module = "com.google.firebase:firebase-perf-ktx" }
firebase-config = { module = "com.google.firebase:firebase-config-ktx" }
firebase-remote-config = { module = "com.google.firebase:firebase-config-ktx", version.ref = "remote_config" }
firebase-common = "com.google.firebase:firebase-common-ktx:20.3.3"
chucker-debug = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-release = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }

work-runtime = "androidx.work:work-runtime-ktx:2.8.1"
hilt-work = "androidx.hilt:hilt-work:1.0.0"
hilt-common = "androidx.hilt:hilt-common:1.0.0"

app-cash-turbine-turbine = "app.cash.turbine:turbine:1.0.0"
junit-androidx = "androidx.test.ext:junit:1.1.5"
junit-androidx-ktx = "androidx.test.ext:junit-ktx:1.1.5"
test-junit-ktx = "androidx.test.ext:junit-ktx:1.1.5"
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

# Dependencies of the included build-logic
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
firebase-performance-gradlePlugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[bundles]
compose = ["coil-compose", "compose-activity", "compose-compiler", "compose-material-3", "compose-materialIcons", "compose-runtimeLivedata", "compose-ui", "compose-ui-util", "compose-ui-tooling", "compose-ui-tooling-preview", "paging-compose", "compose-preview-customview", "compose-preview-customview-poolingcontainer", "compose-constraintlayout", "compose-lifecycle-runtime"]
lifecycle = ["lifecycle-livedataKtx", "lifecycle-runtimeKtx", "lifecycle-viewmodel-compose"]
room = ["room-ktx", "room-paging", "room-runtime"]
ktor = ["ktor-core", "ktor-android", "ktor-json", "ktor-content-negotiation", "ktor-auth", "ktor-logging", "ktor-okhttp"]
firebase = ["firebase-messaging", "firebase-crashlytics", "firebase-analytics", "firebase-performance", "firebase-remote-config", "firebase-common"]
test = ["junit4", "test-junit-ktx"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
detekt = "io.gitlab.arturbosch.detekt:1.19.0"
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
spotless = "com.diffplug.spotless:6.4.2"
toml-checker = "com.github.ben-manes.versions:0.42.0"
toml-updater = "nl.littlerobots.version-catalog-update:0.3.1"
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
