[versions]
android-compile-sdk = "36"
android-min-sdk = "24"
androidx-activity = "1.10.1"
androidx-lifecycle = "2.9.0"
composecompiler = "1.5.15"
coroutines = "1.10.2"
coroutines_datetime = "0.6.2"
desugar_jdk_libs = "2.1.5"
espresso = "3.6.1"
gradleplugin = "8.10.1"
gmsPlugin = "4.4.2"
hilt = "2.56.2"
kotlin = "2.1.21"
ksp = "2.1.21-2.0.2"
lifecycle = "2.9.1"
room = "2.7.1"
ktor = "3.1.3"
splash = "1.0.1"
firebaseCrashlyticsPlugin = "2.9.9"
firebasePerfPlugin = "1.4.2"
junit4 = "4.13.2"
agp = "8.10.1"
chucker = "4.1.0"
androidxComposeBom = "2025.06.00"
remote_config = "22.1.2"
detekt = "1.23.8"
klint = "12.3.0"
spotless = "7.0.4"
app_compat = "1.7.1"
coreKtx = "1.16.0"
hiltsecond = "1.2.0"
runtime = "2.10.1"
material = "1.12.0"
junit = "1.2.1"
coil = "2.7.0"
activity = "1.10.1"
preview_customview = "1.2.0"
poolingcontainer = "1.1.0"
constraintlayout = "1.1.1"
gson = "2.13.1"
swiperefresh = "0.36.0"
auth = "21.3.0"
lottie = "6.6.6"
paging = "3.3.6"
result_jvm = "5.6.0"
datastore = "1.1.7"
timber = "5.0.1"
test_corektx = "1.6.1"
test_robolectric = "4.14.1"
test_navigation = "2.9.0"
test_mockk = "1.14.2"
firebase_bom = "33.15.0"
firebase_common = "21.0.0"
turbine = "1.2.1"
toml_checker = "0.52.0"
toml_updater = "1.0.0"
kotlinStdlib = "2.1.21"
kotlinTest = "2.1.21"
runner = "1.6.2"
core = "1.6.1"

[libraries]
android-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "app_compat" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
android-coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx"}
android-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
android-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
android-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltsecond"}
android-hilt-androidx-compiler = { module = "androidx.hilt:hilt-compiler" ,version.ref = "hiltsecond"}
android-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "runtime"}
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltsecond"}
hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "hiltsecond"}
android-material = { module = "com.google.android.material:material", version.ref = "material"}
android-test-compose = { module = "androidx.compose.ui:ui-test-junit4" }
android-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
android-test-idling = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "espresso" }
android-test-junit4 = { module = "androidx.test.ext:junit", version.ref = "junit"}
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splash" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil"}
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil"}
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity"}
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composecompiler"}
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-materialIcons = { module = "androidx.compose.material:material-icons-extended" }
compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-preview-customview = { module = "androidx.customview:customview", version.ref = "preview_customview"}
compose-preview-customview-poolingcontainer = { module = "androidx.customview:customview-poolingcontainer", version.ref = "poolingcontainer"}
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout"}
compose-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle"}
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "swiperefresh"}
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
gson-gson = { module = "com.google.code.gson:gson", version.ref = "gson"}
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-coroutines-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "coroutines_datetime"}
kotlin-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
gms-play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "auth"}
lifecycle-livedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "paging"}
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging"}
result-jvm = { module = "com.github.kittinunf.result:result-jvm", version.ref = "result_jvm" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore"}
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber"}
test-androidx-core = { module = "androidx.test:core-ktx", version.ref = "test_corektx"}
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "test_robolectric"}
test-navigation = { module = "androidx.navigation:navigation-testing", version.ref = "test_navigation"}
test-mockk = { module = "io.mockk:mockk", version.ref = "test_mockk"}
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase_bom"}
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-performance = { module = "com.google.firebase:firebase-perf-ktx" }
firebase-config = { module = "com.google.firebase:firebase-config-ktx" }
firebase-remote-config = { module = "com.google.firebase:firebase-config-ktx", version.ref = "remote_config" }
firebase-common = { module = "com.google.firebase:firebase-common-ktx", version.ref = "firebase_common"}
chucker-debug = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-release = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }

app-cash-turbine-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine"}
junit-androidx = { module = "androidx.test.ext:junit", version.ref = "junit"}
junit-androidx-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junit"}
test-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junit"}
junit4 = { module = "junit:junit", version.ref = "junit4" }

# Dependencies of the included build-logic
firebase-crashlytics-gradlePlugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
firebase-performance-gradlePlugin = { module = "com.google.firebase:perf-plugin", version.ref = "firebasePerfPlugin" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }


[bundles]
compose = ["coil-compose", "coil-svg", "compose-activity", "compose-compiler", "compose-material3", "compose-materialIcons", "compose-runtimeLivedata", "compose-ui", "compose-ui-util", "compose-ui-tooling", "compose-ui-tooling-preview", "paging-compose", "compose-preview-customview", "compose-preview-customview-poolingcontainer", "compose-constraintlayout", "compose-lifecycle-runtime"]
lifecycle = ["lifecycle-livedataKtx", "lifecycle-runtimeKtx", "lifecycle-viewmodel-compose"]
room = ["room-ktx", "room-paging", "room-runtime"]
ktor = ["ktor-core", "ktor-android", "ktor-json", "ktor-content-negotiation", "ktor-auth", "ktor-logging", "ktor-okhttp"]
firebase = ["firebase-messaging", "firebase-crashlytics", "firebase-analytics", "firebase-performance", "firebase-remote-config", "firebase-common"]
test = ["junit4", "test-junit-ktx"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPlugin" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jlleitschuh = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "klint" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
toml-checker = { id = "com.github.ben-manes.versions", version.ref = "toml_checker" }
toml-updater = { id = "nl.littlerobots.version-catalog-update", version.ref = "toml_updater" }

# Convention plugins defined in the project
droidconke-android-library = { id = "droidconke.android.library", version = "unspecified" }
droidconke-android-room = { id = "droidconke.android.room", version = "unspecified" }
droidconke-android-hilt = { id = "droidconke.android.hilt", version = "unspecified" }
droidconke-android-library-compose = { id = "droidconke.android.library.compose", version = "unspecified" }
droidconke-android-application-firebase = { id = "droidconke.android.application.firebase", version = "unspecified" }
droidconke-android-library-firebase = { id = "droidconke.android.library.firebase", version = "unspecified" }
droidconke-android-application = { id = "droidconke.android.application", version = "unspecified" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
droidconke-android-application-jacoco = { id = "droidconke.android.application.jacoco", version = "unspecified" }
droidconke-android-library-jacoco = { id = "droidconke.android.library.jacoco", version = "unspecified" }